# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Truzt < Formula
  desc "Truzt — secure mesh network client."
  homepage "https://truzt.lk/"
  version "2.7.2"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_darwin_amd64.tar.gz"
      sha256 "2e45b2899be5bea7b14aee995b64767375a3436e80a6f829c4870086dbc5b62e"

      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_darwin_arm64.tar.gz"
      sha256 "672f0e48ef45455621d28b1b2906483c3bc7b5e13cd7cae5f034d8f38e8372f3"

      define_method(:install) do
        bin.install "truzt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_linux_amd64.tar.gz"
      sha256 "bd1f834deed438969b5cc98320b27f4fe8b43e8762e0689359258be2371eaaaa"
      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_linux_armv6.tar.gz"
      sha256 "0c8b237940c40f54ef31305b2c56cd78c752b24daab3c431e91f92fd2564e766"
      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_linux_arm64.tar.gz"
      sha256 "d8b7ab767a591edd10e0e994967124de7839c7179d269633a99b60147e17e795"
      define_method(:install) do
        bin.install "truzt"
      end
    end
  end

  test do
    system "#{bin}/truzt version"
  end
end
