# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Truzt < Formula
  desc "Truzt — secure mesh network client."
  homepage "https://truzt.lk/"
  version "2.8.2"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://pkgs.truzt.lk/release/v2.8.2/truzt_2.8.2_darwin_amd64.tar.gz"
      sha256 "1adaccc0970b020d30dc0cf03ad80a4c4450d378cc96824d893c44f1e277faeb"

      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm?
      url "https://pkgs.truzt.lk/release/v2.8.2/truzt_2.8.2_darwin_arm64.tar.gz"
      sha256 "eee31ac6121cc8e9765e9f818108ac400c46d1afcb4583f3235737c5cf62dc4a"

      define_method(:install) do
        bin.install "truzt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://pkgs.truzt.lk/release/v2.8.2/truzt_2.8.2_linux_amd64.tar.gz"
      sha256 "0af03f93e4249d625e0afadfd77d96a21323b2d2671ec086743de464b136fbfd"
      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://pkgs.truzt.lk/release/v2.8.2/truzt_2.8.2_linux_armv6.tar.gz"
      sha256 "49600a8cf9ea01dbaeaa58664389f6a512813fc8805c88e305051dbac7db68fb"
      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://pkgs.truzt.lk/release/v2.8.2/truzt_2.8.2_linux_arm64.tar.gz"
      sha256 "50f67186d605d15150596094594292a25ad52719c6afcac1e381e8c23905760d"
      define_method(:install) do
        bin.install "truzt"
      end
    end
  end

  test do
    system "#{bin}/truzt version"
  end
end
