# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Truzt < Formula
  desc "Truzt — secure mesh network client."
  homepage "https://truzt.lk/"
  version "2.7.2"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_darwin_amd64.tar.gz"
      sha256 "028f2123340ce5da82850dbf7f2c3d1b02655fbb88545508bfad9c97952e1ee8"

      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_darwin_arm64.tar.gz"
      sha256 "7206796f0f535721fabfe0fdbe43e97a869b34af4f6581a27c723d89f5ae6775"

      define_method(:install) do
        bin.install "truzt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_linux_amd64.tar.gz"
      sha256 "a059be250b4c45705577ca76c55b3678c3eb869068be4bddb6ebae60f4a79922"
      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_linux_armv6.tar.gz"
      sha256 "c1ea5f853ea342b7f8906368c742598ba9a0c8cdc5447a371e589ce77563a071"
      define_method(:install) do
        bin.install "truzt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Zuse-Technologies/Trust/releases/download/v2.7.2/truzt_2.7.2_linux_arm64.tar.gz"
      sha256 "9cfbbef4ac6cdc3f0acf070632365c87fb4d49d19787aa5bf3cb6dd610163873"
      define_method(:install) do
        bin.install "truzt"
      end
    end
  end

  test do
    system "#{bin}/truzt version"
  end
end
